class Config:
    SERVICE_NAME = "SAIV Face Recognition Service"
    VERSION = "1.0.0"

    FACE_DETECTION_MIN_CONFIDENCE = 0.5
    FACE_DETECTION_GOOD_CONFIDENCE = 0.7

    SIMHASH_BITS = 256
    SIMHASH_SEED = 0x5A17
    FACE_MATCH_THRESHOLD = 0.88
    FALLBACK_EMBEDDING_SIZE = 64

    LIVENESS_THRESHOLD = 0.60
    LIVENESS_DEPTH_WEIGHT = 0.30
    LIVENESS_MESH_WEIGHT = 0.25
    LIVENESS_TEXTURE_WEIGHT = 0.25
    LIVENESS_COLOR_WEIGHT = 0.20

    ACTIVE_CHALLENGE_BONUS = 0.15
    PASSIVE_BLINK_BONUS = ACTIVE_CHALLENGE_BONUS / 3
    CHALLENGE_TYPES = ("blink", "head_turn", "mouth_open")
    CHALLENGE_TTL_SECONDS = 60

    DEPTH_GOOD_THRESHOLD = 0.03
    DEPTH_MODERATE_THRESHOLD = 0.01
    BLINK_EAR_THRESHOLD = 0.22
    BLINK_EAR_BASELINE_RATIO = 0.93
    MOUTH_OPEN_MAR_THRESHOLD = 0.30
    HEAD_TURN_RATIO_THRESHOLD = 0.15
    TEXTURE_VARIANCE_SCALE = 500.0
    COLOR_STDDEV_SCALE = 60.0

    SEQUENCE_MIN_FRAMES = 5
    SEQUENCE_MAX_FRAMES = 45
    BLINK_MIN_CLOSED_FRAMES = 2
    HEAD_TURN_MIN_FRAMES = 3
    MOUTH_OPEN_MIN_FRAMES = 3

    RISK_WEIGHTS = {
        "liveness": 0.25,
        "face_match": 0.25,
        "device": 0.20,
        "network": 0.15,
        "geolocation": 0.15,
    }
    RISK_THRESHOLD = 0.50

    NETWORK_PRIVATE_IP_RISK = 0.70
    NETWORK_KEYWORD_RISK = 0.85

    GEO_SPOOF_ACCURACY_METERS = 10
    GEO_VERY_LOW_ACCURACY_METERS = 5000
    GEO_MODERATE_ACCURACY_METERS = 100