"""
Client IP resolution and Singapore IP lookup.

One rule for every caller (rate limiting, audit logs, check-in location
checks): the client is the first X-Forwarded-For address when present,
falling back to the socket address. By default (TRUSTED_PROXIES="*") the
header is honoured from any peer, as the course staff specify. Restricting
TRUSTED_PROXIES to the proxy's networks stops a client connecting directly
from the internet from claiming to be someone else.

Singapore ranges come from app/data/sg_ip_ranges.txt, a DB-IP Lite extract
regenerated by backend/scripts/build_sg_ip_ranges.py. Lookups are offline:
a check-in never waits on a third-party geo-IP API.
"""

import bisect
import ipaddress
import logging
from functools import lru_cache
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union

from fastapi import Request

from app.core.config import settings

logger = logging.getLogger(__name__)

IPAddress = Union[ipaddress.IPv4Address, ipaddress.IPv6Address]

SG_RANGES_FILE = Path(__file__).resolve().parents[1] / "data" / "sg_ip_ranges.txt"

# Addresses that never leave a private network. Check-ins from these are
# treated as on-campus (course staff guidance). Listed explicitly rather than
# using ipaddress.is_private, which also covers the TEST-NET documentation
# ranges (e.g. 203.0.113.0/24) that a test may use as a "foreign" address.
LOCAL_NETWORKS = [
    ipaddress.ip_network(cidr)
    for cidr in (
        "0.0.0.0/8",
        "10.0.0.0/8",
        "100.64.0.0/10",   # carrier-grade NAT
        "127.0.0.0/8",
        "169.254.0.0/16",  # link-local
        "172.16.0.0/12",
        "192.168.0.0/16",
        "::/128",
        "::1/128",
        "fc00::/7",        # unique local
        "fe80::/10",       # link-local
    )
]


def parse_ip(value: Optional[str]) -> Optional[IPAddress]:
    """Parse an address as it appears in a header, tolerating [v6] and :port."""
    if not value:
        return None
    candidate = value.strip()
    if candidate.startswith("["):
        candidate = candidate[1:].split("]", 1)[0]
    elif candidate.count(":") == 1:
        candidate = candidate.split(":", 1)[0]  # IPv4 with a port
    try:
        address = ipaddress.ip_address(candidate)
    except ValueError:
        return None
    if isinstance(address, ipaddress.IPv6Address) and address.ipv4_mapped:
        return address.ipv4_mapped
    return address


@lru_cache(maxsize=1)
def _trusted_networks() -> Tuple[bool, List[ipaddress._BaseNetwork]]:
    trust_all = False
    networks = []
    for entry in settings.trusted_proxies:
        if entry == "*":
            trust_all = True
            continue
        try:
            networks.append(ipaddress.ip_network(entry, strict=False))
        except ValueError:
            logger.error("Ignoring invalid TRUSTED_PROXIES entry %r", entry)
    return trust_all, networks


def _is_trusted_proxy(peer: Optional[IPAddress]) -> bool:
    trust_all, networks = _trusted_networks()
    if trust_all:
        return True
    return peer is not None and any(
        peer.version == net.version and peer in net for net in networks
    )


def client_ip(request: Optional[Request]) -> Optional[str]:
    """
    The caller's IP address.

    First X-Forwarded-For entry when the request came through a trusted
    proxy and that entry is a valid address; otherwise the socket address.
    """
    if request is None:
        return None
    peer_raw = request.client.host if request.client else None
    peer = parse_ip(peer_raw)

    forwarded = request.headers.get("x-forwarded-for")
    if forwarded and _is_trusted_proxy(peer):
        first = parse_ip(forwarded.split(",")[0])
        if first is not None:
            return str(first)

    return str(peer) if peer is not None else peer_raw


def is_local_ip(address: IPAddress) -> bool:
    return any(
        address.version == net.version and address in net for net in LOCAL_NETWORKS
    )


@lru_cache(maxsize=1)
def _sg_ranges() -> Dict[int, Tuple[List[int], List[int]]]:
    """Sorted (starts, ends) per IP version, loaded once."""
    starts: Dict[int, List[int]] = {4: [], 6: []}
    ends: Dict[int, List[int]] = {4: [], 6: []}
    try:
        with SG_RANGES_FILE.open(encoding="utf-8") as handle:
            for line in handle:
                if not line.strip() or line.startswith("#"):
                    continue
                first, last = line.strip().split(",")
                lo, hi = ipaddress.ip_address(first), ipaddress.ip_address(last)
                starts[lo.version].append(int(lo))
                ends[lo.version].append(int(hi))
    except OSError as exc:
        logger.error("Singapore IP ranges unavailable (%s): %s", SG_RANGES_FILE, exc)
    return {v: (starts[v], ends[v]) for v in (4, 6)}


def sg_ranges_loaded() -> bool:
    ranges = _sg_ranges()
    return bool(ranges[4][0] or ranges[6][0])


def is_singapore_ip(address: IPAddress) -> bool:
    starts, ends = _sg_ranges()[address.version]
    value = int(address)
    index = bisect.bisect_right(starts, value) - 1
    return index >= 0 and value <= ends[index]


def ip_outside_singapore(raw: Optional[str]) -> bool:
    """
    True only for a public address that is not in Singapore.

    Private and local addresses count as on-campus. An unparseable address
    or a missing ranges file never blocks a check-in on its own.
    """
    address = parse_ip(raw)
    if address is None or is_local_ip(address):
        return False
    if not sg_ranges_loaded():
        return False
    return not is_singapore_ip(address)
